import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@radix-ui/themes/styles.css';
import Header from "./components/Header";
import { AuthKitProvider } from '@workos-inc/authkit-nextjs';


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Job Board App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="container py-4 px-6 mx-auto">
          <Header />
          <AuthKitProvider>{children}</AuthKitProvider>
          <footer className="text-center p-4 text-gray-500">
              Job board &copy; 2024 - All right reserved
          </footer>
        </main>
      </body>
    </html>
  );
}
